AllCops:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/spec_helper.rb'
  NewCops: enable
Layout/LineLength:
  Max: 100
Metrics/AbcSize:
  Max: 25
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
